/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardZonesRouteImport } from './routes/dashboard/zones'
import { Route as DashboardWorkersRouteImport } from './routes/dashboard/workers'
import { Route as DashboardR2RouteImport } from './routes/dashboard/r2'
import { Route as DashboardPagesRouteImport } from './routes/dashboard/pages'
import { Route as DashboardKvRouteImport } from './routes/dashboard/kv'
import { Route as DashboardAiGatewayRouteImport } from './routes/dashboard/ai-gateway'
import { Route as DashboardWorkersIndexRouteImport } from './routes/dashboard/workers/index'
import { Route as DashboardWorkersIdRouteImport } from './routes/dashboard/workers/$id'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardZonesRoute = DashboardZonesRouteImport.update({
  id: '/zones',
  path: '/zones',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardWorkersRoute = DashboardWorkersRouteImport.update({
  id: '/workers',
  path: '/workers',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardR2Route = DashboardR2RouteImport.update({
  id: '/r2',
  path: '/r2',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPagesRoute = DashboardPagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardKvRoute = DashboardKvRouteImport.update({
  id: '/kv',
  path: '/kv',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAiGatewayRoute = DashboardAiGatewayRouteImport.update({
  id: '/ai-gateway',
  path: '/ai-gateway',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardWorkersIndexRoute = DashboardWorkersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardWorkersRoute,
} as any)
const DashboardWorkersIdRoute = DashboardWorkersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DashboardWorkersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/ai-gateway': typeof DashboardAiGatewayRoute
  '/dashboard/kv': typeof DashboardKvRoute
  '/dashboard/pages': typeof DashboardPagesRoute
  '/dashboard/r2': typeof DashboardR2Route
  '/dashboard/workers': typeof DashboardWorkersRouteWithChildren
  '/dashboard/zones': typeof DashboardZonesRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/workers/$id': typeof DashboardWorkersIdRoute
  '/dashboard/workers/': typeof DashboardWorkersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard/ai-gateway': typeof DashboardAiGatewayRoute
  '/dashboard/kv': typeof DashboardKvRoute
  '/dashboard/pages': typeof DashboardPagesRoute
  '/dashboard/r2': typeof DashboardR2Route
  '/dashboard/zones': typeof DashboardZonesRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/workers/$id': typeof DashboardWorkersIdRoute
  '/dashboard/workers': typeof DashboardWorkersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/ai-gateway': typeof DashboardAiGatewayRoute
  '/dashboard/kv': typeof DashboardKvRoute
  '/dashboard/pages': typeof DashboardPagesRoute
  '/dashboard/r2': typeof DashboardR2Route
  '/dashboard/workers': typeof DashboardWorkersRouteWithChildren
  '/dashboard/zones': typeof DashboardZonesRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/workers/$id': typeof DashboardWorkersIdRoute
  '/dashboard/workers/': typeof DashboardWorkersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/ai-gateway'
    | '/dashboard/kv'
    | '/dashboard/pages'
    | '/dashboard/r2'
    | '/dashboard/workers'
    | '/dashboard/zones'
    | '/dashboard/'
    | '/dashboard/workers/$id'
    | '/dashboard/workers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard/ai-gateway'
    | '/dashboard/kv'
    | '/dashboard/pages'
    | '/dashboard/r2'
    | '/dashboard/zones'
    | '/dashboard'
    | '/dashboard/workers/$id'
    | '/dashboard/workers'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/ai-gateway'
    | '/dashboard/kv'
    | '/dashboard/pages'
    | '/dashboard/r2'
    | '/dashboard/workers'
    | '/dashboard/zones'
    | '/dashboard/'
    | '/dashboard/workers/$id'
    | '/dashboard/workers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/zones': {
      id: '/dashboard/zones'
      path: '/zones'
      fullPath: '/dashboard/zones'
      preLoaderRoute: typeof DashboardZonesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/workers': {
      id: '/dashboard/workers'
      path: '/workers'
      fullPath: '/dashboard/workers'
      preLoaderRoute: typeof DashboardWorkersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/r2': {
      id: '/dashboard/r2'
      path: '/r2'
      fullPath: '/dashboard/r2'
      preLoaderRoute: typeof DashboardR2RouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/pages': {
      id: '/dashboard/pages'
      path: '/pages'
      fullPath: '/dashboard/pages'
      preLoaderRoute: typeof DashboardPagesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/kv': {
      id: '/dashboard/kv'
      path: '/kv'
      fullPath: '/dashboard/kv'
      preLoaderRoute: typeof DashboardKvRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/ai-gateway': {
      id: '/dashboard/ai-gateway'
      path: '/ai-gateway'
      fullPath: '/dashboard/ai-gateway'
      preLoaderRoute: typeof DashboardAiGatewayRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/workers/': {
      id: '/dashboard/workers/'
      path: '/'
      fullPath: '/dashboard/workers/'
      preLoaderRoute: typeof DashboardWorkersIndexRouteImport
      parentRoute: typeof DashboardWorkersRoute
    }
    '/dashboard/workers/$id': {
      id: '/dashboard/workers/$id'
      path: '/$id'
      fullPath: '/dashboard/workers/$id'
      preLoaderRoute: typeof DashboardWorkersIdRouteImport
      parentRoute: typeof DashboardWorkersRoute
    }
  }
}

interface DashboardWorkersRouteChildren {
  DashboardWorkersIdRoute: typeof DashboardWorkersIdRoute
  DashboardWorkersIndexRoute: typeof DashboardWorkersIndexRoute
}

const DashboardWorkersRouteChildren: DashboardWorkersRouteChildren = {
  DashboardWorkersIdRoute: DashboardWorkersIdRoute,
  DashboardWorkersIndexRoute: DashboardWorkersIndexRoute,
}

const DashboardWorkersRouteWithChildren =
  DashboardWorkersRoute._addFileChildren(DashboardWorkersRouteChildren)

interface DashboardRouteChildren {
  DashboardAiGatewayRoute: typeof DashboardAiGatewayRoute
  DashboardKvRoute: typeof DashboardKvRoute
  DashboardPagesRoute: typeof DashboardPagesRoute
  DashboardR2Route: typeof DashboardR2Route
  DashboardWorkersRoute: typeof DashboardWorkersRouteWithChildren
  DashboardZonesRoute: typeof DashboardZonesRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAiGatewayRoute: DashboardAiGatewayRoute,
  DashboardKvRoute: DashboardKvRoute,
  DashboardPagesRoute: DashboardPagesRoute,
  DashboardR2Route: DashboardR2Route,
  DashboardWorkersRoute: DashboardWorkersRouteWithChildren,
  DashboardZonesRoute: DashboardZonesRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
