/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardZonesRouteImport } from './routes/dashboard/zones'
import { Route as DashboardWorkersRouteImport } from './routes/dashboard/workers'
import { Route as DashboardPagesRouteImport } from './routes/dashboard/pages'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardZonesRoute = DashboardZonesRouteImport.update({
  id: '/zones',
  path: '/zones',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardWorkersRoute = DashboardWorkersRouteImport.update({
  id: '/workers',
  path: '/workers',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPagesRoute = DashboardPagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/pages': typeof DashboardPagesRoute
  '/dashboard/workers': typeof DashboardWorkersRoute
  '/dashboard/zones': typeof DashboardZonesRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard/pages': typeof DashboardPagesRoute
  '/dashboard/workers': typeof DashboardWorkersRoute
  '/dashboard/zones': typeof DashboardZonesRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/pages': typeof DashboardPagesRoute
  '/dashboard/workers': typeof DashboardWorkersRoute
  '/dashboard/zones': typeof DashboardZonesRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/pages'
    | '/dashboard/workers'
    | '/dashboard/zones'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard/pages'
    | '/dashboard/workers'
    | '/dashboard/zones'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/pages'
    | '/dashboard/workers'
    | '/dashboard/zones'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/zones': {
      id: '/dashboard/zones'
      path: '/zones'
      fullPath: '/dashboard/zones'
      preLoaderRoute: typeof DashboardZonesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/workers': {
      id: '/dashboard/workers'
      path: '/workers'
      fullPath: '/dashboard/workers'
      preLoaderRoute: typeof DashboardWorkersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/pages': {
      id: '/dashboard/pages'
      path: '/pages'
      fullPath: '/dashboard/pages'
      preLoaderRoute: typeof DashboardPagesRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardPagesRoute: typeof DashboardPagesRoute
  DashboardWorkersRoute: typeof DashboardWorkersRoute
  DashboardZonesRoute: typeof DashboardZonesRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardPagesRoute: DashboardPagesRoute,
  DashboardWorkersRoute: DashboardWorkersRoute,
  DashboardZonesRoute: DashboardZonesRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
